### ISSUE TITLE
Email is passed as _email

### ISSUE THREAD

**Issue by rosszurowski** [segmentio/integration-heap#12]
Hello!

I'm trying to set up Heap through Segment and I noticed that the `email` field from identify calls are being passed to Heap as `_email`. Heap's segments can only be built on special fields (like `email`) rather than custom data (like `_email`), so it's important emails are passed to with the proper name.

For reference, here's an example call to analytics.js that I'm making.

```
analytics.identify('89acfd', {
  name: 'User Name',
  email: 'user@example.com',
  title: 'Position',
  createdAt: '2016-06-06T17:51:59.030-07:00'
})
```

After some searching, I noticed [the PR that caused this behaviour](https://github.com/segment-integrations/integration-heap/pull/2), but wasn't exactly clear why this change was made or how to properly pass emails to Heap.

Any help?

**Comment by kabbi** [comment]
I have the same question. What is the reason for this? @rosszurowski, you may leave answer here if you found it so users from google may get some help.

**Comment by rosszurowski** [comment]
@kabbi I think Heap has since added support for [defining segments based on arbitrary properties](https://cloud.githubusercontent.com/assets/303731/23564090/1899c088-fffe-11e6-8c2d-2b02f30393e2.png). That said, we still have some confusing discrepancies between the `email` field and `_email` in our data thanks to this.

I've re-opened this because I think it would still be nice to fix or understand.

**Comment by ladanazita** [comment]
@rosszurowski @kabbi Hi there! 

I apologize for the delay here. I just chatted with Heap and this was a fix for a legacy issue in Heap where they used to treat `email` as one of Heap's "identity" parameters.

The behavior has been deprecated, however, Segment and Heap have decided to keep the `_email` behavior so as not to separate data for existing customers. We wouldn't want to roll out a change that would cause a break in existing customer reporting. 

The current state still functions, with custom fields working as expected, so while this behavior is annoying, it doesn't seem to be an urgent bug to fix. I will add this to our internal ticket tracking so we can prioritize this later on.

For now, this behavior will remain as we will not prioritize this for the up coming sprint. Feel free to reopen if you have a strong case as to why this should be considered urgent.

Take care

**Comment by fotoflo** [comment]
Hi guys, we are redoing our tracking now and noticed if we put the email address in the ID, it solves this problem.   Is there a better way to get around it?

**Comment by ladanazita** [comment]
@fotoflo This repo has been deprecated. Could you reach out to our support team for assistance? https://segment.com/contact

In general, [we do not suggest](https://segment.com/docs/spec/identify/#user-id) using an email address for the `userId`

Thanks!
