### ISSUE TITLE
Nested attributes are busted

### ISSUE THREAD

**Issue by hurrymaplelad** [segmentio/integration-heap#5]
We're passing a nested object to `track()`: 

``` js
properties: { 
  x: {y: 1} 
}
```

This looks great in the Segment debugger, but Heap is losing the nested attributes in its event filtering UI. Only `x` shows up in the attribute dropdown. I'd expect to see `x.y`. The only recorded value of the `x` attribute is '[object Object]'.

Han helpfully pointed me at this line, likely related to any fix:
https://github.com/segmentio/integration-heap/blob/master/lib/mapper.js#L22

> This is probably because of Heap's limitation on being able to ingest that data.
> But I think flattening them would be something that Segment should do.
> You could submit a PR as well if you'd like.

**Comment by f2prateek** [comment]
Flattening seems reasonable, and I'd also stringily the dates instead of rejecting them outright.

**Comment by hankim813** [comment]
This should've been fixed in this [pr](https://github.com/segment-integrations/integration-heap/pull/6)
